status: Various error reporting improvements
- Added a reusable function for formatting and displaying libhoth_error
- Replaced POSIX with SPIDEV + MTD to be more descriptive and accurate
  - Also removed some internally generated POSIX errors with
    libhoth errors to better indicate the failure source
- Replaced "fw_error" with "EC", as it's more widely known by
- Replace the "FW_EARLGREY" with PIEROT, since other titan
  devices will soon also use this error format.
- Included libusb + posix error formatting strings
- Added tests
- Made the htool output more concise, example:

$ htool --usb_loc 3-3.3 statistics
EC response contained error: 1
Error: 'get_statistics' failed (0x001E000100000001): [CMD_EXEC][EC_RES][INVALID_COMMAND]

Signed-off-by: Steven Portley <sportley@google.com>